---
- name: Build mobile packages for Cinny
  hosts: localhost
  gather_facts: false
  vars_prompt:
  - name: android_key_password
    prompt: "Enter android keystore password"
    private: yes
  tasks:

    - name: Gather app metadata
      block:
        - name: Read tauri.conf.json
          ansible.builtin.slurp:
            src: src-tauri/tauri.conf.json
          register: tauri_config

        - name: Extract app version
          set_fact:
            app_version: "{{ tauri_config['content'] | b64decode | from_json | json_query('version') }}"

        - name: Print extracted version
          debug:
            msg: "Building Cinny version {{ app_version }}"

    - name: Clean previous builds
      block:
        - name: Clean release directory
          ansible.builtin.file:
            path: release/*
            state: absent
        - name: Clean target directory
          ansible.builtin.file:
            path: src-tauri/target
            state: absent

        - name: Clean iOS build
          block:
            - name: Clean build directory
              ansible.builtin.file:
                path: src-tauri/gen/apple/build
                state: absent

            - name: Clean Externals directory
              ansible.builtin.file:
                path: src-tauri/gen/apple/Externals
                state: absent

        - name: Clean Android build
          block:
            - name: Clean build directory
              ansible.builtin.file:
                path: src-tauri/gen/android/app/build
                state: absent

            - name: Delete proguard-tauri.pro
              ansible.builtin.file:
                path: src-tauri/gen/android/app/proguard-tauri.pro
                state: absent

            - name: Delete tauri.build.gradle.kts
              ansible.builtin.file:
                path: src-tauri/gen/android/app/tauri.build.gradle.kts
                state: absent

            - name: Delete tauri.properties
              ansible.builtin.file:
                path: src-tauri/gen/android/app/tauri.properties
                state: absent

            - name: Delete .gradle
              ansible.builtin.file:
                path: src-tauri/gen/android/.gradle
                state: absent

            - name: Delete tauri.settings.gradle
              ansible.builtin.file:
                path: src-tauri/gen/android/tauri.settings.gradle
                state: absent

    - name: Create release directory
      ansible.builtin.file:
        path: release
        state: directory
        mode: '0755'

    - name: Build for iOS
      block:
        - name: iOS build command
          shell: "npm run tauri ios build | tee ios_build.log"
          register: ios_build
          args:
            executable: /bin/bash
        
        - name: Copy .ipa file to release folder
          ansible.builtin.copy:
            src: src-tauri/gen/apple/build/arm64/Cinny.ipa
            dest: release/Cinny-{{ app_version }}.ipa

    - name: Build for Android
      block:
        - name: Get NDK version
          shell: "ls -1 {{ lookup('env', 'HOME') }}/Library/Android/sdk/ndk | tail -n 1"
          register: ndk_version
          changed_when: false

        - name: Android build command
          shell: "npm run tauri android build -- --apk | tee android_build.log"
          environment:
            JAVA_HOME: "/Applications/Android Studio.app/Contents/jbr/Contents/Home"
            ANDROID_HOME: "{{ lookup('env', 'HOME') }}/Library/Android/sdk"
            NDK_HOME: "{{ lookup('env', 'HOME') }}/Library/Android/sdk/ndk/{{ ndk_version.stdout }}"
            ANDROID_KEY_ALIAS: "{{ android_key_alias }}"
            ANDROID_KEY_PASSWORD: "{{ android_key_password }}"
            ANDROID_STORE_FILE: "{{ android_store_file }}"
          args:
            executable: /bin/bash
        
        - name: Copy .apk file to release folder
          ansible.builtin.copy:
            src: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
            dest: release/Cinny-{{ app_version }}.apk

    - name: Generate checksums
      block:
        - name: Generate checksum for release ipa
          ansible.builtin.stat:
            path: "release/Cinny-{{ app_version }}.ipa"
            checksum_algorithm: sha256
          register: ipa_sha256_results

        - name: Save ipa checksum to file
          ansible.builtin.copy:
            content: "{{ ipa_sha256_results.stat.checksum }}"
            dest: "release/Cinny-{{ app_version }}.ipa.sha256"

        - name: Generate checksum for release apk
          ansible.builtin.stat:
            path: "release/Cinny-{{ app_version }}.apk"
            checksum_algorithm: sha256
          register: apk_sha256_results

        - name: Save apk checksum to file
          ansible.builtin.copy:
            content: "{{ apk_sha256_results.stat.checksum }}"
            dest: "release/Cinny-{{ app_version }}.apk.sha256"